<div class="homepage-our-offers" >

 <h4 class="title">Our Offers</h4>
<div class="page-products">
<div class="products-grid">

  <ol class="products list items product-items">
       <li class="item product product-item">                
                    <div class="product-item-info vfront-product-list a-a active" data-container="product-grid">
                         <a href="/armor.html" class="product photo product-item-photo" tabindex="-1">
                        <span class="product-image-container" style="width:240px;">
                            <span class="product-image-wrapper" style="padding-bottom: 90%;">
                                <img class="product-image-photo" src="<?php echo $block->getViewFileUrl('Litslink_CatalogMod::images/armor_img.jpg') ?>" alt="ARMOR"></span>
                        </span>
                    </a>
                    <div class="product details product-item-details">
                          <strong class="product name product-item-name">
                              <a class="product-item-link" href="/armor.html">ARMOR</a>
                          </strong>
                          <div class="product-reviews-summary short">
                            We offfer a wide range of hand crafted
                            armor relating to different periods and
                            regions to protect all
                            parts of the body
                          </div>
                          <div class="product-item-inner">
                              <div class="product actions product-item-actions">
                                  <div class="actions-primary">

                                         <form data-role="tocart-form" action="/armor.html" method="post">
                                              <button class="action primary">
                                                  <span>SHOP NOW</span>
                                              </button>
                                         </form>

                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
       </li>

       <li class="item product product-item">                
                    <div class="product-item-info vfront-product-list a-a active" data-container="product-grid">
                         <a href="/weapon.html" class="product photo product-item-photo" tabindex="-1">
                        <span class="product-image-container" style="width:240px;">
                            <span class="product-image-wrapper" style="padding-bottom: 90%;">
                                <img class="product-image-photo" src="<?php echo $block->getViewFileUrl('Litslink_CatalogMod::images/weapon_img.jpg') ?>" alt="WEAPON"></span>
                        </span>
                    </a>
                    <div class="product details product-item-details">
                          <strong class="product name product-item-name">
                              <a class="product-item-link" href="/weapon.html">WEAPON</a>
                          </strong>
                          <div class="product-reviews-summary short">
                            Combat weapons to participate in your reenactment 
                            of medieval full contact battles
                          </div>
                          <div class="product-item-inner">
                              <div class="product actions product-item-actions">
                                  <div class="actions-primary">
                                         <form data-role="tocart-form" action="/weapon.html" method="post">
                                              <button class="action primary">
                                                  <span>SHOP NOW</span>
                                              </button>
                                         </form>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
       </li>

       <li class="item product product-item">                
                    <div class="product-item-info vfront-product-list a-a active" data-container="product-grid">
                         <a href="/custom-made/" class="product photo product-item-photo" tabindex="-1">
                        <span class="product-image-container" style="width:240px;">
                            <span class="product-image-wrapper" style="padding-bottom: 90%;">
                                <img class="product-image-photo" src="<?php echo $block->getViewFileUrl('Litslink_CatalogMod::images/custom_img.jpg') ?>" alt="CUSTOM MADE"></span>
                        </span>
                    </a>
                    <div class="product details product-item-details">
                          <strong class="product name product-item-name">
                              <a class="product-item-link" href="/custom-made/">CUSTOM MADE</a>
                          </strong>
                          <div class="product-reviews-summary short">
                            We produce armor according to your
                            sketches or pictures in the
                            sources you provide
                          </div>
                          <div class="product-item-inner">
                              <div class="product actions product-item-actions">
                                  <div class="actions-primary">
                                         <form data-role="tocart-form" action="/custom-made/" method="post">
                                              <button class="action primary">
                                                  <span>MAKE AN ORDER</span>
                                              </button>
                                         </form>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
       </li>

       <li class="item product product-item">                
                    <div class="product-item-info vfront-product-list a-a active" data-container="product-grid">
                         <a href="/contact/" class="product photo product-item-photo" tabindex="-1">
                        <span class="product-image-container" style="width:240px;">
                            <span class="product-image-wrapper" style="padding-bottom: 90%;">
                                <img class="product-image-photo" src="<?php echo $block->getViewFileUrl('Litslink_CatalogMod::images/partner_img.jpg') ?>" alt="PARTNERSHIP"></span>
                        </span>
                    </a>
                    <div class="product details product-item-details">
                          <strong class="product name product-item-name">
                              <a class="product-item-link" href="/contact/">PARTNERSHIP</a>
                          </strong>
                          <div class="product-reviews-summary short">
                            We are official partners of the HMB
                            World Championship "Battle of the Nations"
                          </div>
                          <div class="product-item-inner">
                              <div class="product actions product-item-actions">
                                  <div class="actions-primary">
                                         <form data-role="tocart-form" action="/contact/" method="post">
                                              <button class="action primary">
                                                  <span>LEARN MORE</span>
                                              </button>
                                         </form>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
       </li>
  </ol>
</div>  
</div>  
</div><!--//homepage-our-offers-->
