<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success-liqpay-paybutton">
    <?php if ($block->getIsCashondelivery()):?>
      <h4>Send Payment via Liqpay</h4>
      <!--
      <button class="action primary continue">pay</button>
      -->
      <?php echo $block->getLiqpayButton() ?>
    <?php endif;?>
</div>

<style>
  .checkout-success .actions-toolbar {
    display: none;
  }
</style>

