<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;

    // product attributes filter
    $century = $block->getProduct()->getData('century');
    $country = $block->getProduct()->getData('country');

    $items1 = array();
    foreach ($items as $_item) {
            // skip not related products
            // ***
            //var_dump(710314, $century, $steel, get_class($_item), $_item->getData('century'));exit;
            $_item->load($_item->getId());
            if ($_item->getData('century') != $century) continue;
            if ($_item->getData('country') != $country) continue;
            if ($_item->getId() == $block->getProduct()->getId()) continue;

            $items1[] = $_item;
    }
?>
    <?php if ($items1): ?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
        <?php if ($title):?>
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="slider-bestsellers-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 0; ?>
                    <ul class="bxslider-related">
                    <?php foreach ($items1 as $_item): ?>
                        <li>
                          <div class="product-item-info tpl-prod-wdg-content pp-<?php echo $iterator ?>">
                              <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                  <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                              </a>
                              <div class="product-item-details">
                                  <strong class="product-item-name">
                                      <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                         href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                         class="product-item-link">
                                          <?php echo $block->escapeHtml($_item->getName()) ?>
                                      </a>
                                  </strong>
                                  <?php
                                  echo $block->getProductPriceHtml($_item, $type);
                                  ?>

                                  <?php if ($templateType): ?>
                                      <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                  <?php endif; ?>

                                  <?php if ($showWishlist || $showCompare || $showCart): ?>
                                      <div class="product-item-actions">
                                          <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                            <?php $_product = $_item; ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <?php //var_dump('related-prod-530', $postParams, get_class($block));exit; ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                <?php //var_dump(316325, get_class($_product), count($_product->getOptions()), $block->getSubmitUrl($_product));?>
                                                <?php if ($_product->getOptions()): ?>
                                                  <input type="hidden" name="selected_configurable_option" value="" />
                                                <?php endif; ?>
                                                <?php foreach ($_product->getOptions() as $optionItem): ?>
                                                  <input type="hidden" name="options[<?php echo $optionItem->getId() ?>]" value="" />
                                                <?php endforeach; ?>
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                              </div>
                                          <?php endif; ?>
                                          <?php if ($showWishlist || $showCompare): ?>
                                              <div class="actions-secondary" data-role="add-to-links">
                                                  <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                      <a href="#"
                                                         data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                         class="action towishlist" data-action="add-to-wishlist"
                                                         title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                          <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                      </a>
                                                  <?php endif; ?>
                                                  <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                      <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                      <a href="#" class="action tocompare"
                                                         data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                         title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                          <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                      </a>
                                                  <?php endif; ?>
                                              </div>
                                          <?php endif; ?>
                                      </div>
                                  <?php endif; ?>
                              </div>
                          </div>
                        </li>
                    <?php endforeach ?>
                    </ul>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
    <?php endif; ?>
<?php endif;?>

        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
