<!--contacts_icon_block-->
<div class="contacts_icon_block">
<ul class="contacts_icon_list">
  <li>
    <div class="contacts_block call_block">
      <div class="contacts_icon call_icon"></div>
      <h3>Call</h3>
      Chat with our adviser<br /> Monday to Friday:  10 am - 7 pm
      <div class="contacts_item">
        +380.67.535.35.77
      </div>
    </div>
  </li>
  <li>
    <div class="contacts_block email_block">
      <div class="contacts_icon email_icon"></div>
      <h3>Email</h3>
      Chat with our adviser<br /> Monday to Friday: 24/7
      <div class="contacts_item">
        <a href="mailto:sales@ageofcraft.com">sales@ageofcraft.com</a>
      </div>
    </div>
  </li>		
  <li>
    <div class="contacts_block chat_block">
      <div class="contacts_icon chat_icon"></div>
      <h3>Chat</h3>
      Chat with our adviser<br / > Monday to Friday:  10 am - 7 pm
      <div class="contacts_item">
        <a href="#">chat now</a>
      </div>
    </div>
  </li>				
</ul>
</div>
<!--/contacts_icon_block-->
